vet clinic database
ijosue16/vet_clinic-database pull request #1
Opened 2023-02-27 18:41 UTC by ijosue16

In this PR I did the following:

- [ ] created a vet clinic database using Postgres.
- [ ] created a table called animals with its column elements.
- [ ] added data to the animal table.
- [ ] wrote queries to retrieve data due to given conditions.

##Here are the query results screenshots
![create table](https://user-images.githubusercontent.com/111968510/221653287-595d5cb3-da62-4930-a205-afbffeee282b.png)

![Screenshot (18)](https://user-images.githubusercontent.com/111968510/221653380-15ee3443-956f-4487-94ff-3da66a280bcb.png)
![Screenshot (11)](https://user-images.githubusercontent.com/111968510/221653389-37a05a96-16e3-4877-9907-2b934ab5eb00.png)
![Screenshot (12)](https://user-images.githubusercontent.com/111968510/221653390-ac4f2043-dd1e-4f15-8762-cf3c43de94b5.png)
![Screenshot (20)](https://user-images.githubusercontent.com/111968510/221653696-fc385e13-c621-4c7c-8f57-8e48361d59f2.png)
![Screenshot (14)](https://user-images.githubusercontent.com/111968510/221653393-41a84012-0262-4761-afd5-60de3cebe5e9.png)
![Screenshot (15)](https://user-images.githubusercontent.com/111968510/221653398-85f02314-81ab-4261-8c21-6d42d93f18be.png)
![Screenshot (16)](https://user-images.githubusercontent.com/111968510/221653401-dfa56d1a-b514-4216-aa8e-1f4de8e96b12.png)
![Screenshot (17)](https://user-images.githubusercontent.com/111968510/221653403-566c82d1-4e9c-4424-a319-fb29aa609fd7.png)

2023-02-27 18:50 UTC, rloterh reviewed
Hi Iradukunda, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Kindly ensure that provided placeholder texts/ guide instructions are removed and/or replaced with appropriate contents applicable under each section of your ReadMe. Similarly, kindly also remove guide notes for _license_ creation under the _license_ section.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-02-27 20:33 UTC, Deepakdanger requested changes
Hi @ijosue16 , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-27 20:33 UTC, Deepakdanger commented on schema.sql
> +id BIGSERIAL NOT NULL,
- [x] Kindly also mark `id` as primary key

2023-02-27 20:33 UTC, Deepakdanger commented on schema.sql
> +weight_kg FLOAT(30));
- [x] Here `weight_kg` should be type `DECIMAL`.Kindly change it

2023-02-28 05:28 UTC, ijosue16 commented on schema.sql
> +weight_kg FLOAT(30));
all changes applied using queries


![Screenshot (23)](https://user-images.githubusercontent.com/111968510/221762372-b333e0e9-4e4d-4602-b983-e36e1f2d51e2.png)

2023-02-28 05:58 UTC, MeqdamAlqudah approved these changes
Hi @ijosue16 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://user-images.githubusercontent.com/74744787/221767026-288e9b01-832d-4d0d-a93b-2a8e3ee72a11.png)

## Highlights 
:+1: no linter errors 
:+1: Changes requested by the last reviewer implemented 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-28 06:11 UTC, merged